services:
  - type: web
    name: carhome
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ALIYUN_ACCESS_KEY_ID
        sync: false
      - key: ALIYUN_ACCESS_KEY_SECRET
        sync: false
      - key: ALIYUN_REGION_ID
        value: cn-shanghai
      - key: ALIYUN_STUDIO_RETURN_FORM
        value: whiteBK
      - key: PHOTOROOM_API_KEY
        sync: false
      - key: REMOVE_BG_API_KEY
        sync: false
